---
functional: # Функциональные требования
  - Игроки должны иметь возможность соревноваться друг с другом в решении задач
  - Игроки должны видеть написание кода друг у друга в реальном времени
  - Игроки могут играть с ботом
  - Игроки могут играть с другом по ссылке
  - На сайте должен веститсь рейтинг по играм
  - Игроки должны иметь возможность выбирать языки для решения задач
  - Игроки должны иметь возможность общаться с соперником и зрителями в чате
  - Правильность решения задачи должно определяться тестами
  - Игроки должны иметь возможность сами создавать игру
  - Игроки должны иметь возможность вступать в открытые игры в качестве соперника
  - Игроки должны иметь возможность  вступать в запущенные игры в качестве зрителя
non-functional: # Нефункциональные требования
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit: # Неявные требования
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Задачи для игроков необходимо обновлять и дополнять
  - Задачи должны быть сформулированы четко и понятно
  - Необходимо регулярно обновлять сайт, дополняя новыми функциями, исправляя баги и делая улучшения
  - Пользовательский интерфейс должен быть интуитивно понятным и удобным для использования
